---
- import_tasks: ubuntu.yml
  when: ansible_os_family == "Debian"

- import_tasks: darwin.yml
  when: ansible_os_family == "Darwin"

- import_tasks: arch.yml
  when: ansible_os_family == "Archlinux"

- include_tasks: variables.yml
  with_items: "{{ variables }}"

- name: Erase fish_user_path
  shell: fish --command 'set --erase fish_user_paths'
  check_mode: no
  changed_when: False
  ignore_errors: True

- name: Apply PATH
  shell: fish --command 'set --universal fish_user_paths {{ item }} $fish_user_paths'
  changed_when: False
  with_items: "{{ paths }}"

- name: Check install fisherman
  shell: type fisher
  register: exist_fisherman
  failed_when: False

- name: Install fisherman
  shell: curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs https://git.io/fisher
  when: exist_fisherman.rc != 0

- name: Create symlink
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - src: "{{ ansible_env.PWD }}/config/fish/config.fish"
      dest: "{{ ansible_user_dir }}/.config/fish/config.fish"
    - src: "{{ ansible_env.PWD }}/config/fish/fishfile"
      dest: "{{ ansible_user_dir }}/.config/fish/fishfile"
