---
- name: Install zplug
  homebrew:
    name: zplug
    state: present
  when: ansible_os_family == "Darwin"

- name: Check installed zplug
  stat:
    path: "{{ ansible_user_dir }}/.local/share/zplug"
  register: exist_zplug
  ignore_errors: False

- name: Install zplug
  shell: "curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh"
  when: not exist_zplug.stat.exists
