pull_request_rules:
  - name: Merge using the merge queue
    conditions:
      - and:
        - or:
            - "author=renovate[bot]"
            - "author=raba-jp"
        - "base=main"
        - "check-success=build"
    actions:
      queue:
        name: default
        merge_method: squash
        update_method: merge
  - name: Automatic update
    conditions:
      - -conflict
      - -draft
    actions:
      update:
