name: "Setup nix and tools"
inputs:
runs:
  using: "composite"
  steps:
    - name: "Install nix"
      uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: "Print nix info"
      shell: bash
    - run: nix-shell -p nix-info --run "nix-info -m"
    - name: "Setup cachix"
      uses: cachix/cachix-action@v10
      with:
        name: raba-jp
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
