name: "Setup nix and tools"
inputs:
  github-access-token:
    required: true
    description: "GitHub Personal Access Token"
  cachix-auth-token:
    required:  true
    description: "Cachix Auth Token"
runs:
  using: "composite"
  steps:
    - name: "Install nix"
      uses: cachix/install-nix-action@v16
      with:
        install_url: https://releases.nixos.org/nix/nix-2.6.0/install
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ inputs.github-access-token }}
    - name: "Setup cachix"
      uses: cachix/cachix-action@v10
      with:
        name: raba-jp
        authToken: ${{ inputs.cachix-auth-token }}
    - run: nix-env -iA nix-build-uncached
      shell: bash
