---
- name: Setup
  hosts: all
  connection: local
  vars_files:
    - vars/main.yml
  roles:
    - { role: mac, tags: [mac], when: ansible_os_family == "Darwin" }
    - { role: arch, tags: [arch], when: ansible_os_family == "Archlinux" }
    - { role: clojure, tags: [clojure] }
    - { role: go, tags: [go] }
    - { role: ruby, tags: [ruby] }
    - { role: python, tags: [python] }
    - { role: rust, tags: [rust] }
    - { role: node, tags: [node] }
    - { role: dart, tags: [dart] }
    - { role: git, tags: [git] }
    - { role: fish, tags: [fish] }
    - { role: vscode, tags: [vscode] }
    - { role: inkdrop, tags: [inkdrop] }
    - { role: docker, tags: [docker] }
    - { role: tmux, tags: [tmux] }
    - { role: vim, tags: [vim] }
    - { role: alacritty, tags: [alacritty] }
    - { role: xkeysnail, tags: [xkeysnail] }
