[config]
skip_core_tasks = true

[tasks.fmt]
command = 'treefmt'

[tasks.build.linux]
script = '''
#!/usr/bin/env bash
sudo nixos-rebuild switch
'''

[tasks.build.mac]
script = '''
#!/usr/bin/env bash
nix build './#darwinConfigurations.SakurabaMBP.system'
./result/sw/bin/darwin-rebuild switch --flake ./
'''

[tasks.generate.linux]
script = '''
#!/usr/bin/env bash
dconf dump / | dconf2nix > home/dconf.nix
'''

[tasks.update]
script = '''
#!/usr/bin/env bash
nix flake update
'''

[tasks.check]
script = '''
#!/usr/bin/env bash
nix-shell -p nix-info --run "nix-info -m"
'''

[tasks.crypt]
script = '''
#!/usr/bin/env bash
gpg --import gpg-public.keys.backup
gpg --import --allow-secret-key-import gpg-private.keys.backup
gpg --import-ownertrust trust.txt
'''
