[config]
skip_core_tasks = true

[tasks.format]
script = '''
#!/usr/bin/env bash
fd --extension nix . | xargs nixfmt
fd --extension sh . | xargs shfmt -w
fd --extension lua . | xargs lua-format -i
'''

[tasks.build.linux]
script = '''
#!/usr/bin/env bash
sudo nixos-rebuild switch
'''

[tasks.build.mac]
script = '''
#!/usr/bin/env bash
nix build './#darwinConfigurations.SakurabaMBP.system'
./result/sw/bin/darwin-rebuild switch --flake ./
'''

[tasks.setup.mac]
script = '''
#!/usr/bin/env bash
nix-build https://github.com/LnL7/nix-darwin/archive/master.tar.gz -A installer
./result/bin/darwin-installer
nix-env -iA nixpkgs.nixUnstable
'''

[tasks.install.mac]
script = '''
#!/usr/bin/env bash
curl -L https://nixos.org/nix/install | sh -s -- --darwin-use-unencrypted-nix-store-volume --daemon
'''

[tasks.generate.linux]
script = '''
#!/usr/bin/env bash
dconf dump / | dconf2nix > home/dconf.nix
'''

[tasks.update]
script = '''
#!/usr/bin/env bash
nix flake update
'''
