[config]
skip_core_tasks = true

[tasks.format]
script = '''
#!/usr/bin/env bash
fd --extension nix . | xargs nixfmt
fd --extension sh . | xargs shfmt -w
fd --extension lua . | xargs lua-format -i
'''

[tasks.build.linux]
script = '''
#!/usr/bin/env bash
sudo nixos-rebuild switch
'''

[tasks.build.mac]
script = '''
#!/usr/bin/env bash
nix build './#darwinConfigurations.SakurabaMBP.system'
./result/sw/bin/darwin-rebuild switch --flake ./
'''

[tasks.generate.linux]
script = '''
#!/usr/bin/env bash
dconf dump / | dconf2nix > home/dconf.nix
'''

[tasks.update]
script = '''
#!/usr/bin/env bash
nix flake update
'''
