[config]
skip_core_tasks = true

[tasks.format]
script = '''
#!/usr/bin/env bash
fd --extension nix . | xargs nixfmt
'''

[tasks.build.linux]
script = '''
#!/usr/bin/env bash
sudo nixos-rebuild switch
'''

[tasks.build.mac]
script = '''
#!/usr/bin/env bash
nix build './#darwinConfigurations.SakurabaMBP.system'
./result/sw/bin/darwin-rebuilt switch --flake ./
'''

[tasks.generate.mac]
script = '''
#!/usr/bin/env bash
dconf dump / | dconf2nix > home/dconf.nix
'''
