[config]
skip_core_tasks = true

[tasks.format]
command = "treefmt"

[tasks.switch]
script = ['''
#!/usr/bin/env bash
sudo nixos-rebuild switch --flake .#$(hostname)
''']

[tasks.mkpart]
command = "disko"
args = ["--mode zap_create_mount", "./nixos/hosts/xps/disk.nix"]

[tasks.install]
command = "nixos-install"
args = ["--flake", ".#xps"]

[tasks.help]
description = "List all available commands"
command = "makers"
args = ["--list-all-steps"]
