[formatter.deadnix]
command = "deadnix"
options = ["-e"]
includes = ["*.nix"]
excludes = []

[formatter.nix]
command = "alejandra"
options = []
includes = ["*.nix"]
excludes = []

[formatter.lua]
command = "stylua"
options = []
includes = ["*.lua"]
excludes = []

[formatter.sh]
command = "shfmt"
options = ["-w"]
includes = ["*.sh"]
excludes = []

[formatter.toml]
command = "taplo"
options = ["fmt"]
includes = ["*.toml"]
excludes = []
