#!/bin/zsh
if [ -n "$BUFFER" ]; then
	zle accept-line
	return 0
fi

[ "$WIDGET" != "$LASTWIDGET" ] && enter_count=0

case $[enter_count++] in
	0)
		echo
		echo -e "\e[0;33m--- list files ---\e[0m"
		ls -alG
		if [ "$(git rev-parse --is-inside-work-tree 2> /dev/null)" = 'true' ]; then
			echo
			echo -e "\e[0;33m--- git status ---\e[0m"
			git status --short --branch
			echo
			echo
		fi
		zle reset-prompt
		;;
	1)
		unset enter_count
		;;
esac
return 0
