# brew
pkg "bat"
pkg "ctags"
pkg "exa"
pkg "fd"
pkg "fish"
pkg "ghq"
pkg "jq"
pkg "nkf"
pkg "less"
pkg "vim"
pkg "peco"
pkg "rg"
pkg "reattach-to-user-namespace"
pkg "stern"
pkg "tree"
pkg "wget"

# brew cask
pkg "cask alfred"
pkg "cask android-studio"
pkg "cask bartender"
pkg "cask clipy"
pkg "cask dash"
pkg "cask docker"
pkg "cask font-cica"
pkg "cask font-myrica"
pkg "cask google-chrome"
pkg "cask google-cloud-sdk"
pkg "cask hyperswitch"
pkg "cask inkdrop"
pkg "cask mplayerx"
pkg "cask quicklook-csv"
pkg "cask qlmarkdown"
pkg "cask slack"
pkg "cask the-unarchiver"
