# brew
pkg "less"
pkg "reattach-to-user-namespace"
pkg "stern"
pkg "wget"

# brew cask
pkg "cask alfred"
pkg "cask android-studio"
pkg "cask bartender"
pkg "cask clipy"
pkg "cask dash"
pkg "cask docker"
pkg "cask homebrew/cask-fonts/font-cica"
pkg "cask homebrew/cask-fonts/font-myrica"
pkg "cask google-chrome"
pkg "cask google-cloud-sdk"
pkg "cask hyperswitch"
pkg "cask inkdrop"
pkg "cask mplayerx"
pkg "cask quicklook-csv"
pkg "cask qlmarkdown"
pkg "cask slack"
pkg "cask the-unarchiver"
