# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [(modulesPath + "/installer/scan/not-detected.nix")];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/dfe138f7-473a-4caa-afa6-eea958828fda";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/DEDC-4FB5";
    fsType = "vfat";
  };

  swapDevices = [{device = "/dev/disk/by-uuid/6f4a20cf-6ade-40f7-84d3-abc8d272bc16";}];

  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
