##############################
###            Go          ###
##############################
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = '''
  let g:go_fmt_command = "goimports"
  let g:go_highlight_functions = 1
  let g:go_highlight_methods = 1
  let g:go_highlight_structs = 1
  let g:go_highlight_operators = 1
  let g:go_highlight_build_constraints = 1
'''

[[plugins]]
repo = 'jodosha/vim-godebug'
on_ft = 'go'

##############################
###           Ruby         ###
##############################
[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = 'ruby'

[[plugins]]
repo = 'vim-utils/vim-ruby-fold'
on_ft = 'ruby'
hook_source = '''
  let g:ruby_fold_lines_limit = 100
'''

[[plugins]]
repo = 'todesking/ruby_hl_lvar.vim'
on_ft = 'ruby'

##############################
###        JavaScript      ###
##############################
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'


##############################
###         Python         ###
##############################
[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
##############################
###          YAML          ###
##############################
[[plugins]]
repo = 'stephpy/vim-yaml'
on_ft = 'yaml'

##############################
###          TOML          ###
##############################
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

##############################
###          HAML          ###
##############################
[[plugins]]
repo = 'tpope/vim-haml'
on_ft = 'haml'

##############################
###          JSON          ###
##############################
[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

##############################
###          Slim          ###
##############################
[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

##############################
###        Dockerfile      ###
##############################
[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = 'dockerfile'

##############################
###        Markdown        ###
##############################
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'

[[plugins]]
repo = 'iamcco/markdown-preview.vim'
on_ft = 'markdown'
