##############################
###       Denite.nvim      ###
##############################
[[plugins]]
repo = 'Shougo/denite.nvim'
if = "has('nvim')"
if = "has('python3')"
hook_source = '''
nnoremap <silent> <Leader>do :<C-u>Denite file_rec<CR>
nnoremap <silent> <Leader>dm :<C-u>Denite file_mru<CR>
nnoremap <silent> <Leader>dy :<C-u>Denite neoyank<CR>
nnoremap <silent> <Leader>dl :<C-u>Denite line<CR>
nnoremap <silent> <Leader>dg :<C-u>Denite grep<CR>
'''
hook_post_source = '''
call denite#custom#var('grep', 'command', ['ag', '--nogroup', '--nocolor', '--smart-case', '--hidden'])
call denite#custom#var('grep', 'default_opts', [])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'separator', ['--'])
call denite#custom#source('file_rec, grep', 'matcher', ['matcher_cpsm'])
call denite#custom#map('_', '-', '<denite:do_action:split>')
call denite#custom#map('_', '|', '<denite:do_action:vsplit>')
call denite#custom#map('insert', 'jj', '<denite:enter_mode:normal>')
'''

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'tsukkee/unite-tag'

##############################
###        Terminal        ###
##############################
repo ='kassio/neoterm' 
if = "has('nvim')"
hook_source = '''
  let g:neoterm_position = 'horizontal'
  let g:neoterm_repl_ruby = 'pry'
'''

##############################
###      Input support     ###
##############################
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

##############################
###         Matcher        ###
##############################
[[plugins]]
repo = 'nixprime/cpsm'
