##############################
###     Plugin Manager    ####
##############################
[[plugins]]
repo = 'Shougo/dein.vim'

##############################
###      Color Scheme      ###
##############################
[[plugins]]
repo = 'lifepillar/vim-solarized8'
hook_add = '''
  colorscheme solarized8_dark
'''

##############################
###        EasyMotion      ###
##############################
[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
  let g:EasyMotion_smartcase = 1
  let g:EasyMotion_do_mapping = 0
  nmap <Space>l <Plug>(easymotion-lineforward)
  nmap sj <Plug>(easymotion-j)
  nmap sk <Plug>(easymotion-k)
  nmap sh <Plug>(easymotion-linebackward)
  nmap ss <Plug>(easymotion-overwin-f2)
'''

##############################
###      Syntax Check      ###
##############################
[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok']
'''

##############################
###       Status Line      ###
##############################
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = ''' execute 'source' g:plugins_home . '/lightline/init.rc.vim' '''

##############################
###           Ctags        ###
##############################
[[plugins]]
repo = 'soramugi/auto-ctags.vim'
hook_add = '''
let g:auto_ctags = 1
let g:auto_ctags_directory_list = ['tmp']
let g:auto_ctags_filetype_mode = 1
'''

##############################
###      Fuzzy search      ###
##############################
[[plugins]]
repo = 'haya14busa/incsearch.vim'
hook_add = '''
map /  <Plug>(incsearch-forward)
map ?  <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)
'''

##############################
###    Context FileType    ###
##############################
[[plugins]]
repo = 'Shougo/context_filetype.vim' 

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'Shougo/context_filetype.vim'

##############################
###     Editor Config      ###
##############################
[[plugins]]
repo = 'editorconfig/editorconfig-vim'

##############################
###        Web API         ###
##############################
[[plugins]]
repo = 'mattn/webapi-vim'

##############################
###         Crowi          ###
##############################
[[plugins]]
repo = 'b4b4r07/vim-crowi'
hook_add = '''
  let g:crowi#api_url = "https://private-wiki.herokuapp.com"
  let g:crowi#access_token = "wqLAwdN1nGkWehS4svK0HLWQuq1Jiv5UfCTBnIjzAkM="
  let g:crowi#filetypes = ['markdown']
  let g:crowi#open_page = true
  let g:crowi#default_create_path = '/user/sakuraba/memo'
  let g:crowi#browser_command = 'open'
'''
