##############################
###       Denite.nvim      ###
##############################
[[plugins]]
repo = 'Shougo/denite.nvim'
if = "has('nvim')"
if = "has('python3')"
on_i = 1
hook_add = ''' execute 'source' g:plugins_home . '/denite/init.rc.vim' '''
hook_post_source = ''' execute 'source' g:plugins_home . '/denite/loaded.rc.vim' '''

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'tsukkee/unite-tag'

##############################
###         Snippet        ###
##############################
[[plugins]]
repo = 'Shougo/neosnippet'
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']'
hook_source = '''
imap <C-k> <Plug>(neosnippet_expand_or_jump)
smap <C-k> <Plug>(neosnippet_expand_or_jump)
xmap <C-k> <Plug>(neosnippet_expand_target)
if has('conceal')
  set conceallevel=2 concealcursor=niv
endif
'''

##############################
###      Input support     ###
##############################
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

##############################
###      Auto Complete     ###
##############################
[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"
if = 'has("python3")'
on_i = 1
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  execute 'source' g:plugins_home . '/deoplete/init.rc.vim'
'''

[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_ft = 'go'
depends = 'deoplete.nvim'
hook_add = ''' execute 'source' g:plugins_home . '/deoplete/go.rc.vim' '''

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = 'ruby'
depends = 'deoplete.nvim'

[[plugins]]
repo = 'zchee/deoplete-zsh' 
on_ft = 'zsh'
depends = 'deoplete.nvim'

##############################
###         Matcher        ###
##############################
[[plugins]]
repo = 'nixprime/cpsm'
