##############################
###     Plugin Manager    ####
##############################
[[plugins]]
repo = 'Shougo/dein.vim'

##############################
###      Color Scheme      ###
##############################
[[plugins]]
repo = 'altercation/vim-colors-solarized'
hook_add = '''
  set background=dark
  let g:solarized_termtrans = 1
  let g:solarized_termcolors = 256
  augroup ColorScheme
    autocmd!
    au ColorScheme VimEnter * nested colorscheme solarized
  augroup END
'''

##############################
###        EasyMotion      ###
##############################
[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
  let g:EasyMotion_smartcase = 1
  let g:EasyMotion_do_mapping = 0
  nmap <Space>l <Plug>(easymotion-lineforward)
  nmap sj <Plug>(easymotion-j)
  nmap sk <Plug>(easymotion-k)
  nmap sh <Plug>(easymotion-linebackward)
  nmap ss <Plug>(easymotion-overwin-f2)
'''

##############################
###      Syntax Check      ###
##############################
[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok']
'''

##############################
###       Status Line      ###
##############################
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = ''' execute 'source' g:plugins_home . '/lightline/init.rc.vim' '''

##############################
###           Ctags        ###
##############################
[[plugins]]
repo = 'soramugi/auto-ctags.vim'
hook_add = '''
let g:auto_ctags = 1
let g:auto_ctags_directory_list = ['tmp']
let g:auto_ctags_filetype_mode = 1
'''

##############################
###      Fuzzy search      ###
##############################
[[plugins]]
repo = 'haya14busa/incsearch.vim'
hook_add = '''
map /  <Plug>(incsearch-forward)
map ?  <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)
'''

##############################
###    Context FileType    ###
##############################
[[plugins]]
repo = 'Shougo/context_filetype.vim' 

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'Shougo/context_filetype.vim'

##############################
###     Editor Config      ###
##############################
[[plugins]]
repo = 'editorconfig/editorconfig-vim'
