##############################
###       Denite.nvim      ###
##############################
[[plugins]]
repo = 'Shougo/denite.nvim'
if = "has('nvim')"
if = "has('python3')"
hook_add = ''' execute 'source' g:plugins_home . '/denite/init.rc.vim' '''
hook_post_source = ''' execute 'source' g:plugins_home . '/denite/loaded.rc.vim' '''

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'tsukkee/unite-tag'

##############################
###        Terminal        ###
##############################
repo ='kassio/neoterm' 
if = "has('nvim')"
hook_source = '''
  let g:neoterm_position = 'horizontal'
  let g:neoterm_repl_ruby = 'pry'
'''

##############################
###      Input support     ###
##############################
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

##############################
###      Auto Complete     ###
##############################
[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"
if = 'has("python3")'
on_i = 1
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  execute 'source' g:plugins_home . '/deoplete/init.rc.vim'
'''

[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_ft = 'go'
depends = 'deoplete.nvim'
hook_add = ''' execute 'source' g:plugins_home . '/deoplete/go.rc.vim' '''

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = 'ruby'
depends = 'deoplete.nvim'

[[plugins]]
repo = 'zchee/deoplete-zsh' 
on_ft = 'zsh'
depends = 'deoplete.nvim'

##############################
###         Matcher        ###
##############################
[[plugins]]
repo = 'nixprime/cpsm'
