set encoding=utf-8
scriptencoding utf-8

let g:mapleader = "\<Space>"

let g:config_home = empty($XDG_CONFIG_HOME) ? expand('~/.config') : $XDG_CONFIG_HOME
let g:plugins_home = g:config_home . '/vim/plugins'

let &runtimepath = g:config_home .','. &runtimepath

let s:dein_init_file = g:config_home . '/vim/dein_init.vim'
let s:mapping_file = g:config_home . '/vim/mapping.vim'
let s:commons_file = g:config_home . '/vim/commons.vim'

execute 'source' s:dein_init_file
execute 'source' s:mapping_file
execute 'source' s:commons_file
