---
- name: Update packages
  apt:
    update_cache: yes

- name: Install package
  apt:
    name: "{{ item }}"
    state: present
    autoclean: yes
    autoremove: yes
  with_items: "{{ apt_packages }}"
