---
- name: Update homebrew
  homebrew:
    update_homebrew: yes

- name: Install Visual Studio Code
  homebrew_cask:
    name: visual-studio-code
    state: latest

- import_tasks: file.yml
  with_items: "{{ darwin_vscode_config_files }}"
