---
- name: for macOS
  import_tasks: darwin.yml
  when: ansible_os_family == "Darwin"

- name: for Ubuntu
  import_tasks: ubuntu.yml
  when: ansible_os_family == "Debian"

- include_tasks: extension.yml
  with_items: "{{ vscode_extensions }}"
