---
- import_tasks: darwin.yml
  when: ansible_os_family == "Darwin"

- import_tasks: arch.yml
  when: ansible_os_family == "Archlinux"

- include_tasks: extension.yml
  with_items: "{{ vscode_extensions }}"
