### Plugin Manager
[[plugins]]
repo = 'Shougo/dein.vim'

### Color Scheme
[[plugins]]
repo = 'lifepillar/vim-solarized8'
if = "$TERM == 'xterm-256color:Tc'"
hook_add = ''' colorscheme solarized8_dark '''

[[plugins]]
repo = 'altercation/vim-colors-solarized'
if = "$TERM != 'xterm-256color:Tc'"
hook_add = '''
  set background=dark
  let g:solarized_termtrans = 1
  let g:solarized_termcolors = 256
  augroup ColorScheme
    autocmd!
    au ColorScheme VimEnter * nested colorscheme solarized
  augroup END
'''

### Syntax
[[plugins]]
repo = 'w0rp/ale'
hook_add = ''' let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok'] '''

[[plugins]]
repo = 'KeitaNakamura/highlighter.nvim'
hook_add = ''' let g:highlighter#auto_update = 2 '''

### Status Line
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = ''' execute 'source' g:config_home . '/nvim/plugins/lightline/init.rc.vim' '''

### Ctags
[[plugins]]
repo = 'soramugi/auto-ctags.vim'
hook_add = '''
  let g:auto_ctags = 1
  let g:auto_ctags_directory_list = ['tmp']
  let g:auto_ctags_filetype_mode = 1
'''

### Incremental search
[[plugins]]
repo = 'haya14busa/incsearch.vim'
hook_add = '''
  map /  <Plug>(incsearch-forward)
  map ?  <Plug>(incsearch-backward)
  map g/ <Plug>(incsearch-stay)
'''

### Change filetype from context
[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'Shougo/context_filetype.vim'

### Visual Mode
[[plugins]]
repo = 'terryma/vim-expand-region'
hook_add = '''
  vmap v <Plug>(expand_region_expand)
  vmap <C-v> <Plug>(expand_region_shrink)
'''

[[plugins]]
repo = 'rhysd/clever-f.vim'

### Snippet
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet'
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
  let g:go_fmt_command = "goimports"
  let g:go_highlight_functions = 1
  let g:go_highlight_methods = 1
  let g:go_highlight_structs = 1
  let g:go_highlight_operators = 1
  let g:go_highlight_build_constraints = 1
'''

[[plugins]]
repo = 'jodosha/vim-godebug'
on_ft = 'go'

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = 'ruby'

[[plugins]]
repo = 'vim-utils/vim-ruby-fold'
on_ft = 'ruby'
hook_source = ''' let g:ruby_fold_lines_limit = 100 '''

[[plugins]]
repo = 'todesking/ruby_hl_lvar.vim'
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-fugitive'
