---
- import_tasks: darwin.yml
  when: ansible_os_family == "Darwin"

- import_tasks: ubuntu.yml
  when: ansible_os_family == "Debian"

- import_tasks: arch.yml
  when: ansible_os_family == "Archlinux"

- name: Create symlink
  file:
    src: "{{ ansible_env.PWD }}/config/clojure"
    dest: "{{ ansible_user_dir }}/.config/clojure"
    state: link
