---
- name: Update cache
  apt:
    update_cache: yes
  become: yes

- name: Install Python
  apt:
    name:
      - python-dev
      - python-pip
      - python-setuptools
      - python3-dev
      - python3-pip
      - python3-setuptools
    state: present
    autoclean: yes
    autoremove: yes
  become: yes
