---
- name: Update cache
  apt:
    update_cache: yes
  become: yes

- name: Install Python
  apt:
    name: "{{ item }}"
    state: present
    autoclean: yes
    autoremove: yes
  become: yes
  with_items:
    - python-dev
    - python-pip
    - python-setuptools
    - python3-dev
    - python3-pip
    - python3-setuptools
