{ inputs, config, pkgs, ... }: {
  homebrew = {
    casks = [
      "alacritty"
      "alfred"
      "appcleaner"
      "bartender"
      "bettertouchtool"
      "bitwarden"
      "clipy"
      "dash"
      "deepl"
      "discord"
      "docker"
      "eul"
      "font-hackgen"
      "font-myrica"
      # "google-chrome"
      "hammerspoon"
      "hyperswitch"
      "intellij-idea"
      "kitty"
      "obsidian"
      "osxfuse"
      "qlmarkdown"
      "quicklook-csv"
      "redisinsight"
      # "slack"
      "stack-stack"
      "tableplus"
      "tandem"
      "the-unarchiver"
      "visual-studio-code"
      "zoom"
    ];
  };
}
