---
homebrew_taps:
  - homebrew/services
  - caskroom/cask
  - caskroom/fonts
  - neovim/neovim
  - go-delve/delve
  - c-bata/kube-prompt
  - wata727/tflint

homebrew_packages:
  - bash-completion
  - boost
  - brew-cask-completion
  - bundler-completion
  - cargo-completion
  - ctags
  - docker-compose-completion
  - exa
  - fd
  - fish
  - gem-completion
  - git
  - ghq
  - name: gnu-sed
    install_options: with-default-names
  - jq
  - kube-prompt
  - kubernetes-helm
  - nkf
  - less
  - neovim
  - peco
  - pip-completion
  - rails-completion
  - rake-completion
  - ruby-completion
  - reattach-to-user-namespace
  - rustc-completion
  - terminal-notifier
  - terraform
  - tflint
  - sshrc
  - the_silver_searcher
  - tig
  - tmux
  - tree
  - wget

homebrew_cask_packages:
  - alfred
  - android-studio
  - bartender
  - clipy
  - dash
  - docker
  - font-cica
  - font-myrica
  - google-chrome
  - google-cloud-sdk
  - hyperswitch
  - inkdrop
  - kitty
  - mplayerx
  - music-manager
  - quicklook-csv
  - qlmarkdown
  - slack
  - the-unarchiver

mac_os_defaults:
  # 半透明メニューバー
  - domain: NSGlobalDomain
    key: AppleEnableMenuBarTransparency
    type: bool
    value: true

  # ウィンドウが開閉時のアニメーション
  - domain: NSGlobalDomain
    key: NSAutomaticWindowAnimationsEnabled
    type: bool
    value: true

  # 保存ダイアログ 常に詳細な情報を開いて表示
  - domain: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode
    type: bool
    value: true

  # iCloud対応アプリでiCloudをデフォルトの保存先にしない
  - domain: NSGlobalDomain
    key: NSDocumentSaveNewDocumentsToCloud
    type: bool
    value: false

  # "... 開いてもよろしいですか" を表示しない
  - domain: com.apple.LaunchServices
    key: LSQuarantine
    type: bool
    value: false

  # ascii 制御文字を表示する
  - domain: NSGlobalDomain
    key: NSTextShowsControlCharacters
    type: bool
    value: true

  # アプリケーションを終了して再度開くときにウィンドウを復元しない
  - domain: NSGlobalDomain
    key: NSQuitAlwaysKeepsWindows
    type: bool
    value: false

  # automatic termination 機能の無効化
  - domain: NSGlobalDomain
    key: NSDisableAutomaticTermination
    type: bool
    value: true

  # クラッシュリポーターダイアログを表示しない
  - domain: com.apple.CrashReporter
    key: DialogType
    type: string
    value: "none"

  # ヘルプを常時前面表示しない
  - domain: com.apple.helpviewer
    key: DevMode
    type: bool
    value: true

  # アップデートのチェック周期 1日
  - domain: com.apple.SoftwareUpdate
    key: ScheduleFrequency
    type: int
    value: 1

  # トラックパッドをタップ = 常時クリック
  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Clicking
    type: int
    value: 1

  - domain: NSGlobalDomain 
    host: currentHost
    key: com.apple.mouse.tapBehavior
    type: int
    value: 1

  - domain: NSGlobalDomain
    key: com.apple.mouse.tapBehavior
    type: int
    value: 1

  - domain: com.apple.AppleMultitouchTrackpad
    key: Clicking
    type: int
    value: 1

  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadCornerSecondaryClick
    type: int
    value: 2

  # 副ボタンのクリック = 右下端をクリック
  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadRightClick
    type: bool
    value: true

  - domain: NSGlobalDomain
    host: currentHost
    key: com.apple.trackpad.trackpadCornerClickBehavior
    type: int
    value: 1

  - domain: NSGlobalDomain
    host: currentHost
    key: com.apple.trackpad.enableSecondaryClick
    type: bool
    value: true

# Trackpad: swipe between pages with three fingers
  # ページ間をスワイプ 3本指でスワイプ
  - domain: NSGlobalDomain
    key: AppleEnableSwipeNavigateWithScrolls
    type: bool
    value: true

  - domain: NSGlobalDomain
    host: currentHost
    key: com.apple.trackpad.threeFingerHorizSwipeGesture
    type: int
    value: 1

  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadThreeFingerHorizSwipeGesture
    type: int
    value: 1

  # スクロールの方向 ナチュラル
  - domain: NSGlobalDomain
    key: com.apple.swipescrolldirection
    type: bool
    value: true

  # フルキーボードアクセス すべてのコントロール
  - domain: NSGlobalDomain
    key: AppleKeyboardUIMode
    type: int
    value: 3

  # キーのリピートの速さ 最速
  - domain: NSGlobalDomain
    key: KeyRepeat
    type: int
    value: 2

  - domain: NSGlobalDomain
    key: InitialKeyRepeat
    type: int
    value: 15

  # 環境光が暗い場合にキーボードの輝度を調整 オン
  - domain: com.apple.BezelServices
    key: kDim
    type: bool
    value: true

  # 発光した状態で待機する時間 30秒
  - domain: com.apple.BezelServices
    key: kDimTime
    type: int
    value: 30

  # スクリーンセーバー解除時のパスワード要求 する
  - domain: com.apple.screensaver
    key: askForPassword
    type: int 
    value: 1

  # スクリーンセーバーに入ってから何秒後にパスワードを要求するか 0秒
  - domain: com.apple.screensaver
    key: askForPasswordDelay
    type: float
    value: 0

  # スクリーンショットの出力先
  - domain: com.apple.screencapture
    key: location
    type: string 
    value: "$HOME/Desktop"

  # スクリーンショットのフォーマット png
  - domain: com.apple.screencapture
    key: type
    type: string
    value: "png"

  # スクリーンショットの影付き効果 なし
  - domain: com.apple.screencapture
    key: disable-shadow
    type: bool
    value: true

  # [Finder] メニューに [Finder を終了] アイテムの表示
  - domain: com.apple.finder
    key: QuitMenuItem
    type: bool
    value: true

  ### [Finder の環境設定]，pnl[一般] > [デスクトップに表示する項目]
  # [ハードディスク]       -> "オン"
  # [外部ディスク]         -> "オン"
  # [CD，DVD，および iPod] -> "オン"
  # [接続しているサーバ]   -> "オン"
  - domain: com.apple.finder
    key: ShowExternalHardDrivesOnDesktop
    type: bool
    value: true

  - domain: com.apple.finder
    key: ShowHardDrivesOnDesktop
    type: bool
    value: true

  - domain: com.apple.finder
    key: ShowMountedServersOnDesktop
    type: bool
    value: true

  - domain: com.apple.finder
    key: ShowRemovableMediaOnDesktop
    type: bool
    value: true

  # すべてのファイル名拡張子を表示
  - domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true

  # ステータスバーを表示
  - domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true

  # パスバーを表示
  - domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true

  # QuickLook でのテキストコンテンツ編集
  - domain: com.apple.finder
    key: QLEnableTextSelection
    type: bool
    value: true

  # タイトルバーへのパス表示 する
  - domain: com.apple.finder
    key: _FXShowPosixPathInTitle
    type: bool
    value: true

  # 検索時に現在のフォルダ内を検索
  - domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: "SCcf"

  # 拡張子を変更する前に警告を表示しない
  - domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false

  # ネットワーク接続時の .DS_Store ファイル生成の抑制
  - domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true

  #ディスクイメージ .dmg 展開時の検証処理のスキップ
  - domain: com.apple.frameworks.diskimages 
    key: skip-verify
    type: bool
    value: true

  - domain: com.apple.frameworks.diskimages
    key: skip-verify-locked
    type: bool
    value: true

  - domain: com.apple.frameworks.diskimages
    key: skip-verify-remote
    type: bool
    value: true

  # ボリュームのマウント時，新しいファインダで開く
  - domain: com.apple.frameworks.diskimages
    key: auto-open-ro-root
    type: bool
    value: true

  - domain: com.apple.frameworks.diskimages
    key: auto-open-rw-root
    type: bool
    value: true

  - domain: com.apple.finder
    key: OpenWindowForNewRemovableDisk
    type: bool
    value: true

  # グリッド表示時の Dock のスタック上のマウスオーバー時のハイライト
  - domain: com.apple.dock
    key: mouse-over-hilite-stack
    type: bool
    value: true

  # 起動済みのアプリケーションにインジケータ・ランプを表示
  - domain: com.apple.dock
    key: show-process-indicators
    type: bool
    value: true

  # ウィンドウをアプリケーションごとにグループ化
  - domain: com.apple.dock
    key: expose-group-by-app
    type: bool 
    value: true

  # dashboard を無効にする
  - domain: com.apple.dashboard
    key: mcx-disabled
    type: bool
    value: true

  # 最新の使用状況に基づいて操作スペースを自動的に並び替える
  - domain: com.apple.dock
    key: mru-spaces
    type: bool
    value: false

  # 隠れているアプリケーションの dock のアイコン透過
  - domain: com.apple.dock
    key: showhidden
    type: bool
    value: true

# Hot corners
# Possible values:
#  0: no-op
#  2: Mission Control
#  3: Show application windows
#  4: Desktop
#  5: Start screen saver
#  6: Disable screen saver
#  7: Dashboard
# 10: Put display to sleep
# 11: Launchpad
# 12: Notification Center
# Top left screen corner → Mission Control
  - domain: com.apple.dock
    key: wvous-tl-corner
    type: int
    value: 5

  - domain: com.apple.dock
    key: wvous-tl-modifier
    type: int
    value: 0

  - domain: com.apple.dock
    key: wvous-tr-corner
    type: int
    value: 12

  - domain: com.apple.dock
    key: wvous-tr-modifier
    type: int
    value: 0

  - domain: com.apple.dock
    key: wvous-bl-corner
    type: int
    value: 0

  - domain: com.apple.dock
    key: wvous-bl-modifier
    type: int
    value: 0

  - domain: com.apple.dock
    key: wvous-br-corner
    type: int
    value: 0

  - domain: com.apple.dock
    key: wvous-br-modifier
    type: int
    value: 0
