---
- include_tasks: ubuntu.yml
  when: ansible_os_family == "Debian"

- include_tasks: darwin.yml
  when: ansible_os_family == "Darwin"

- include_tasks: variables.yml
  with_items: "{{ variables }}"

- name: Erase fish_user_path
  shell: fish --command 'set --erase fish_user_paths'
  check_mode: no
  changed_when: False
  ignore_errors: True

- name: Apply PATH
  shell: fish --command 'set --universal fish_user_paths {{ item }} $fish_user_paths'
  changed_when: False
  with_items: "{{ paths }}"
