---
- name: Install nodenv and plugins
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  with_items:
    - repo: https://github.com/nodenv/nodenv
      dest: "{{ xdg_data_home }}/nodenv"
    - repo: https://github.com/nodenv/node-build
      dest: "{{ xdg_data_home }}/nodenv/plugins/node-build"

- name: Setup nodenv
  shell: |
    cd {{ xdg_data_home }}/nodenv && \
    src/configure && \
    make -C src

- name: Check Node.js
  stat:
    path: "{{ xdg_data_home }}/nodenv/shims/node"
  register: node

- name: Install Node
  shell: |
    NODENV_ROOT={{ xdg_data_home }}/nodenv \
    {{ xdg_data_home }}/nodenv/bin/nodenv install {{ node_version }}
  when: not node.stat.exists

- name: nodenv rehash
  shell: |
    NODENV_ROOT={{ xdg_data_home }}/nodenv \
    {{ xdg_data_home }}/nodenv/bin/nodenv rehash
  when: not node.stat.exists

- name: nodenv global
  shell: |
    NODENV_ROOT={{ xdg_data_home }}/nodenv \
    {{ xdg_data_home }}/nodenv/bin/nodenv global {{ node_version }}
  when: not node.stat.exists

- name: nodenv rehash
  shell: |
    NODENV_ROOT={{ xdg_data_home }}/nodenv \
    {{ xdg_data_home }}/nodenv/bin/nodenv rehash
  when: not node.stat.exists

- name: Install Node.js package
  npm:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('latest') }}"
    global: yes
    executable: "{{ xdg_data_home }}/nodenv/shims/npm"
  with_items: "{{ node_packages }}"

- name: nodenv rehash
  shell: |
    NODENV_ROOT={{ xdg_data_home }}/nodenv \
    {{ xdg_data_home }}/nodenv/bin/nodenv rehash
