---
- name: Remove
  pacman:
    name: firefox
    state: absent
  become: yes

- name: Install
  pacman:
    name:
      - autoconf
      - automake
      - base-devel
      - binutils
      # IME
      - fcitx
      - fcitx-configtool
      - fcitx-mozc
      - fcitx-gtk3
      # Gnome3 Theme
      - materia-gtk-theme
      - gnome-themes-extra
      - gtk-engine-murrine
      # Tools
      - git
      - exa
      - fd
      - ripgrep
      - fish
      - kubectl
      - kubectx
      - tig
      - tmux
      - yay
      - vim
      - caprine
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - noto-fonts-extra
    update_cache: yes
  become: yes

# direnv peco

- name: Create config dir
  file:
    path: "{{ ansible_user_dir }}/.config"
    state: directory
    recurse: yes

- name: Create directory
  file:
    path: "{{ ansible_user_dir }}/.ansible/plugins/modules"
    state: directory
    recurse: yes

- name: Create AUR build user
  user:
    name: aur_builder
    group: wheel
  become: yes

- name: Modify sudoers
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: yes
    validate: "visudo -cf %s"
  become: yes

- name: Install from AUR
  aur:
    name:
      - peco
      - direnv
      - google-chrome
      - ttf-cica
      - ttf-hackgen
      - station
      - starship
  become: yes
  become_user: aur_builder

- name: Copy file
  file:
    src: "{{ ansible_env.PWD }}/xprofile"
    dest: "{{ ansible_user_dir }}/.xprofile"
    state: link
