---
- name: Install
  pacman:
    name: "{{ item }}"
  with_items:
    - autoconf
    - automake
    - base-devel
    - binutils
    # IME
    - fcitx
    - fcitx-configtool
    - fcitx-mozc
    - fcitx-gtk3
    # Gnome3 Theme
    - materia-gtk-theme
    - gnome-themes-extra
    - gtk-engine-murrine
    # Tools
    - git
    - direnv
    - exa
    - fd
    - ripgrep
    - fish
    - kubectl
    - kubectx
    - peco
    - tig
    - tmux
    - yay
  become: yes

- name: Create config dir
  file:
    path: "{{ ansible_user_dir }}/.config"
    state: directory
    recurse: yes
