---
- name: Check
  stat:
    path: "{{ gopath }}/src/{{ item }}"
  register: check
  ignore_errors: True

- name: Get package
  shell: "go get -u {{ item }}"
  environment:
    GOPATH: "{{ gopath }}"
  when: not check.stat.exists
