---
- import_tasks: ubuntu.yml
  when: ansible_os_family == "Debian"

- import_tasks: darwin.yml
  when: ansible_os_family == "Darwin"

- include_tasks: install_package.yml
  with_items: "{{ go_packages }}"
