if [ -z $ZSHEMV_LOADED ]; then
  # XDG BASE DIRECTORY
  export XDG_CONFIG_HOME=$HOME/.config
  export XDG_CACHE_HOME=$HOME/.cache
  export XDG_DATA_HOME=$HOME/.local/share

  export LESSHISTFILE=$XDG_CACHE_HOME/less/history
  export MPLAYER_HOME=$XDG_CONFIG_HOME/mplayer
  export INPUTRC=$XDG_CONFIG_HOME/readline/inputrc
  export ZDOTDIR=$XDG_CONFIG_HOME/zsh
  export EDITOR=nvim

  # zplug
  export ZPLUG_HOME=$XDG_DATA_HOME/zplug
  export ZPLUG_LOADFILE=$XDG_CONFIG_HOME/zsh/packages.zsh
  export ZPLUG_USE_CACHE=true
  export ZPLUG_CACHE_DIR=$XDG_CACHE_HOME/zplug

  # Go
  export GOPATH=$HOME/Development
  export GO15VENDOREXPERIMENT=1

  if [ $(uname) = 'Darwin' ]; then
    # Google Cloud SDK
    export GCPPATH=/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk
    export ANDROID_SDK_TOOLS=$HOME/Library/Android/sdk/tools
    export ANDROID_SDK_PLATFORM_TOOLS=$HOME/Library/Android/sdk/platform-tools
  fi

  export SYS_NOTIFIER=/usr/local/bin/terminal-notifier
  export CARGO_HOME=$XDG_DATA_HOME/cargo
  export RUSTUP_HOME=$XDG_DATA_HOME/rustup
  export RBENV_ROOT=$XDG_DATA_HOME/rbenv
  export NODENV_ROOT=$XDG_DATA_HOME/nodenv

  ##### Path #####
  path=(
  $GCPPATH(N-/)
  $GOPATH/bin(N-/)
  $RBENV_ROOT/bin(N-/)
  $NODENV_ROOT/bin(N-/)
  $ANDROID_SDK_TOOLS(N-/)
  $ANDROID_SDK_PLATFORM_TOOLS(N-/)
  $RUSTUP_HOME(N-/)
  $CARGO_HOME(N-/)
  $path
  )

  [ -f $ZSH_CONF_DIR/.zshenv.secure ] && source $ZSH_CONF_DIR/.zshenv.secure

  fpath=(
    $ZDOTDIR/functions
    $ZDOTDIR/completion
    $fpath
  )

  export ZSHENV_LOADED=1

else
  echo '.zshenv load skipped'
fi

