- name: Check config file
  stat:
    path: "{{ item.dest }}"
  register: check
  changed_when: False

- name: Remove config file
  file:
    path: "{{ item.dest }}"
    state: absent
  when: not check.stat.islnk

- name: Create symlink
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
