---
- name: Install dependencies
  import_tasks: dependencies.yml

- name: Install nodenv and plugins
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  with_items:
    - repo: https://github.com/nodenv/nodenv
      dest: "{{ ansible_user_dir }}/.nodenv"
    - repo: https://github.com/nodenv/node-build
      dest: "{{ ansible_user_dir }}/.nodenv/plugins/node-build"

- name: Check Node.js
  stat:
    path: "{{ ansible_user_dir }}/.nodenv/shims/node"
  register: node

- name: Install Node
  shell: "{{ ansible_user_dir }}/.nodenv/bin/nodenv install {{ node_version }}"
  when: not node.stat.exists

- name: nodenv rehash
  shell: "{{ ansible_user_dir }}/.nodenv/bin/nodenv rehash"
  when: not node.stat.exists

- name: nodenv global
  shell: "{{ ansible_user_dir }}/.nodenv/bin/nodenv global {{ node_version }}"
  when: not node.stat.exists

- name: nodenv rehash
  shell: "{{ ansible_user_dir }}/.nodenv/bin/nodenv rehash"
  when: not node.stat.exists
