[tool.poetry]
name = "machinectl"
version = "0.1.0"
description = ""
authors = ["Hiroki Sakuraba <feath.7615@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
typer = "^0.4.1"
platformdirs = "2.5.1"

[tool.poetry.dev-dependencies]
black = "^22.3.0"

[tool.poetry.scripts]
machinectl = 'machinectl:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
