---
- name: import mackerel GPG key
  apt_key:
    url: https://mackerel.io/assets/files/GPG-KEY-mackerel
    state: present

- name: add repository 'mackerel'
  apt_repository:
    repo: deb http://apt.mackerel.io/debian/ mackerel contrib
    state: present
    update_cache: yes

- name: install mackerel-agent
  apt:
    name: mackerel-agent
    state: latest
    update_cache: yes

- name: copy config file
  template:
    src: ../templates/mackerel-agent.conf.j2
    dest: "{{ ubuntu_agent_config_path }}"
  when: not mackerel_api_key
