---
- name: Install docker for Arch Linux
  pacman:
    name:
      - docker
      - docker-compose
    update_cache: yes
  become: yes

- name: Start docker daemon
  systemd:
    name: docker.service
    state: started
    enabled: yes
  become: yes
