---
- name: Install docker for Arch Linux
  pacman:
    name:
      - docker
      - docker-compose
    update_cache: yes
  become: yes

- name: Add user to docker group
  user:
    name: "{{ ansible_env.USER }}"
    append: yes
    groups:
      - docker

- name: Start docker daemon
  systemd:
    name: docker.service
    state: started
    enabled: yes
  become: yes

- name: microk8s
  snap:
    name: microk8s
    classic: yes
    channel: edge

- name: Add user to microk8s group
  user:
    name: "{{ ansible_env.USER }}"
    append: yes
    groups:
      - microk8s
