---
- name: Install neovim
  pacman:
    name: neovim
    update_cache: yes
  become: yes

- name: Create symlink
  file:
    src: "{{ ansible_env.PWD }}/config/nvim"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    state: link
