---
- import_tasks: darwin.yml
  when: ansible_os_family == "Darwin"
- import_tasks: arch.yml
  when: ansible_os_family == "Archlinux"

- name: Create symlink
  file:
    src: "{{ ansible_env.PWD }}/config/alacritty"
    dest: "{{ ansible_user_dir }}/.config/alacritty"
    state: link
