---
- name: Update cache
  apt:
    update_cache: yes
  become: yes

- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
    autoclean: yes
    autoremove: yes
  become: yes
  with_items:
    - build-essential
    - curl
    - libssl-dev
    - libreadline-dev
    - zlib1g-dev
