name: benchmark
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-benchmark
  cancel-in-progress: true

jobs:
  activate:
    name: Activate home-manager configuration
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
        with:
          github-access-token: ${{ secrets.GITHUB_TOKEN }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: |
          nix build --no-link '.#homeConfigurations.runner.activationPackage'
          "$(nix path-info '.#homeConfigurations.runner.activationPackage')"/activate
      - run: go install github.com/rhysd/vim-startuptime@latest
      - name: Run benchmark
        run: nix run .#machinectl -- benchmark > result.json
      - name: Dump outputs
        run: cat result.json
      - name: Upload benchmark
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: customSmallerIsBetter
          output-file-path: result.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          comment-on-alert: true
          fail-on-alert: true
          alert-threshold: '150%'
          alert-comment-cc-users: '@raba-jp'
