name: Build
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  builds:
    name: Build nixos configuration
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
        with:
          github-access-token: ${{ secrets.GITHUB_TOKEN }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build -f deploy.nix -o deploy-spec.json
      - uses: actions/upload-artifact@v2
        with:
          name: deploy-spec
          path: |
            deploy-spec.json
  activate:
    name: Activate deployment
    runs-on: ubuntu-20.04
    needs: builds
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
        with:
          github-access-token: ${{ secrets.GITHUB_TOKEN }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - uses: actions/download-artifact@v2
        with:
          name: deploy-spec
          path: deploy-spec.json
      - name: Activate
        if: ${{ github.ref == 'refs/heads/main' }}
        run: cachix deploy activate deploy-spec.json
        env:
          CACHIX_ACTIVATE_TOKEN: ${{ secrets.CACHIX_ACTIVATE_TOKEN }}
