name: Build 
on:
  pull_request:
  push:
    branches:
      - main

concurrency: 
  group: ${{ github.ref }}-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@v21
        with:
          nix_on_tmpfs: true
          nix_conf: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            system-features = kvm
      - uses: nixbuild/nixbuild-action@v15
        with:
          nixbuild_ssh_key: ${{ secrets.NIXBUILD_NET_SSH_KEY }}
      - name: Build
        run: |
          touch build.json
          nix build \
            --eval-store auto \
            --store ssh-ng://eu.nixbuild.net \
            --builders '' --max-jobs 2 \
            .#nixosConfigurations.define7.config.system.build.toplevel \
            --json > build.json
      - name: Create deploy spec file
        run: |
          jq '.[0].outputs.out | { agents: {define7: .}}' build.json > spec.json
      - uses: actions/upload-artifact@v3
        with:
          name: result
          path: |
            spec.json
