name: Build 
on:
  pull_request:
  push:
    branches:
      - main

concurrency: 
  group: ${{ github.ref }}-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v10
        with:
          name: raba-jp
          extraPullNames: helix
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build -L .#deploySpec
      - uses: actions/upload-artifact@v3
        with:
          name: result
          path: |
            result
