name: "Check flake"
on:
  push:
    paths:
      - flake.nix
      - flake.lock
  pull_request:
    paths:
      - flake.nix
      - flake.lock
jobs:
  check:
    name: 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: nix flake check
