name: Build
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  builds:
    name: Build nixos configuration
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
        with:
          github-access-token: ${{ secrets.GITHUB_TOKEN }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build
      - uses: actions/upload-artifact@v2
        with:
          name: result
          path: |
            result
  activate:
    name: Activate deployment
    runs-on: ubuntu-20.04
    needs: builds
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
        with:
          github-access-token: ${{ secrets.GITHUB_TOKEN }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - uses: actions/download-artifact@v2
        with:
          name: result
      - name: Activate
        run: cachix deploy activate ./result
        env:
          CACHIX_ACTIVATE_TOKEN: ${{ secrets.CACHIX_ACTIVATE_TOKEN }}
