name: Update Dependencies
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron:  '0 18 * * *' # runs daily at JST 00:00

jobs:
  lockfile:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v12
        with:
          token: ${{ secrets.PAT }}
