name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron:  '0 9 * * *' # runs daily at 09:00

jobs:
  lockfile:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v6
        with:
          token: ${{ secrets.PAT }}
