name: Go

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-10.14]
    steps:
      - uses: actions/checkout@v1
      - name: Provisioning
        run: ./setup.sh ruby
        env:
          GOPATH: /home/runner/dev
      - name: Install serverspec
        run: ./setup_test.sh
      - name: Run Serverspec
        run: rake spec:go
        env:
          GOPATH: /home/runner/dev
