name: CI

on: [push]

jobs:
  arch:
    runs-on: ubuntu-latest
    container: archlinux/base:latest
    steps:
      - uses: actions/checkout@v1
      - name: Update packages
        run: pacman -Syu --noconfirm
      - name: Install required packages
        run: pacman -S --noconfirm git tar sudo
      - name: Install dotfiles
        run: ./init.sh /home/runner/work/dotfiles/dotfiles
