name: NixOS build and activate
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: 
  group: ${{ github.ref }}-nixos
  cancel-in-progress: true

jobs:
  build:
    name: Build nixos configuration
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
        with:
          github-access-token: ${{ secrets.GITHUB_TOKEN }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - uses: nixbuild/nixbuild-action@v8
        with:
          nixbuild_ssh_key: ${{ secrets.NIX_BUILD_SSH_KEY }}
      - run: nix build -L
      - uses: actions/upload-artifact@v2
        with:
          name: result
          path: |
            result
  activate:
    name: Activate deployment
    runs-on: ubuntu-20.04
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
        with:
          github-access-token: ${{ secrets.GITHUB_TOKEN }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - uses: actions/download-artifact@v2
        with:
          name: result
      - name: Activate
        run: cachix deploy activate ./result
        env:
          CACHIX_ACTIVATE_TOKEN: ${{ secrets.CACHIX_ACTIVATE_TOKEN }}
