name: Update Dependencies
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron:  '0 18 * * *' # runs daily at JST 00:00

jobs:
  lockfile:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v12
        with:
          token: ${{ secrets.PAT }}
  brave-browser:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - run: go run scripts/brave-updater/main.go
      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          branch: bump-brave-version
          delete-branch: true
          title: Bump Brave browser version
          token: ${{ secrets.PAT }}
