name: Update Dependencies
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron:  '0 15 * * 5'

jobs:
  lockfile:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v24
        with:
          token: ${{ secrets.PAT }}
